### ISSUE TITLE
Oo please add for collaboration

### ISSUE THREAD

**Issue by abhi18av** [A-Infinite/DataScience-DelhiSmog2016Analysis#1]
@arushi-bhatt and @aditikr158 

You needed to add me to this organization for collaboration here. 

We'll be working on the projects together if you wish.

**Comment by arushi-bhatt** [comment]
bhaiya
on basecamp or on github or on both?

**Comment by abhi18av** [comment]
Hmm, that's up to you.

Did you get the basecamp student license yet?

Well, I see no harm in being added here.

**Comment by arushi-bhatt** [comment]
no license,
we signed in for trial period

**Comment by arushi-bhatt** [comment]
I have invited you on github A-infinite organization
and also on basecamp , use this link
https://3.basecamp.com/3850726/join/BSK6qkg1nMJN

**Comment by abhi18av** [comment]
@arushi-bhatt  delete the link asap

**Comment by arushi-bhatt** [comment]
comment deleted :)

**Comment by abhi18av** [comment]
👍
